[workspace]
resolver = "2"

members = [
    "crawler",
    "db", 
    "embedder", 
    "parser", "search", 
    "utils",
]

[workspace.dependencies]
db = { path = "db" }
utils = { path = "utils" }
embedder = { path = "embedder" }

