services:
  foxeyedb:
    build:
      dockerfile: ./db/Dockerfile
    container_name: foxeyedb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=foxeyedb
      - POSTGRES_PASSWORD=foxeye
      - POSTGRES_USER=foxeye
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: foxeye_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: foxeye_amq
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=foxeye
      - RABBITMQ_DEFAULT_PASS=foxeye_amq
